name = "leiasabores-api"
main = "functions/index.ts"
compatibility_date = "2025-01-01"

# Cloudflare Pages build output
pages_build_output_dir = "./dist"

[vars]
FRONTEND_URL = "https://leiasabores.pt"
STRIPE_SECRET_KEY = "sk_test_51SKDZ2Pp8rvygrajLMupMz5rD4Q5bFSqaATAP5U4a2We9z30j6pK5gSCsyKVk8dbgdbrUg7oagpKPWqLWWZnRqUj00o1SlaToM"
STRIPE_WEBHOOK_SECRET = "whsec_GprwB9efI4m2EH3j1GTc80Fyqwt2GR9b"
JWT_SECRET = "dev_secret_change_me"

[triggers]
crons = ["*/5 * * * *"]

[[d1_databases]]
binding = "DB"
database_name = "leiasabores_d1"
database_id = "63f7de3e-2605-46ea-8a58-8d1d9e8d8007"
preview_database_id = "637fde3e-2605-46ea-8a58-8d1d9e8d8007"

[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = "leiasabores-assets"

[[kv_namespaces]]
binding = "CART_KV"
id = "COLOQUE_SEU_KV_ID_AQUI"

# [durable_objects]
# bindings = [
#   { name = "SESSION_DO", class_name = "SessionDurableObject" }
# ]

# [[migrations]]
# tag = "v1"
# new_classes = [ "SessionDurableObject" ]

[ai]
binding = "AI"
